version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@4.0.1
  aws-ecs: circleci/aws-ecs@0.0.8
workflows:
  build_and_deploy_image:
    jobs:
      - build_and_push_image
      - deploy_image_to_service:
          requires: 
            - build_and_push_image
jobs:
  build_and_push_image:
    docker:
      - image: circleci/python:3-stretch
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          checkout: true
          create-repo: true
          dockerfile: repo/Dockerfile
          extra-build-args: "--build-arg GITHUB_USER=${GITHUB_USER} --build-arg GITHUB_TOKEN=${GITHUB_TOKEN} --build-arg BRANCH_NAME=${CIRCLE_BRANCH} --build-arg SETTINGS_NAME=magic_pod.settings_development --build-arg AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} --build-arg AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} --build-arg BUCKET_URL=${CREDENTIALS_BUCKET_URL}"
          account-url: AWS_ECR_ACCOUNT_URL
          repo: "${AWS_RESOURCE_NAME_PREFIX}"
          region: AWS_DEFAULT_REGION
          tag: "latest"  
  deploy_image_to_service:
    docker:
      - image: circleci/python:3-stretch
    steps:
      - aws-ecs/update-service:
           family: "sample-repo-task"
           cluster-name: "sample-repo-cluster"
           service-name: "sample-repo-service"
           container-image-name-updates: "container=sample-repo,tag=latest"
#jobs:
#  build_and_push_image:
#      - aws-ecs/deploy-service-update:
#        aws-region: ${AWS_DEFAULT_REGION}
#        family: "${AWS_RESOURCE_NAME_PREFIX}-service"
#        cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
#        container-image-name-updates: container=${AWS_RESOURCE_NAME_PREFIX}-service,tag=${CIRCLE_SHA1}"


#      - aws-ecs/update-service:
#          family: "${AWS_RESOURCE_NAME_PREFIX}-service"
#          cluster-name: "${AWS_RESOURCE_NAME_PREFIX}-cluster"
#          container-image-name-updates: "container=${AWS_RESOURCE_NAME_PREFIX}-service,image-and-tag=${FULL_IMAGE_NAME}"
#          container-env-var-updates: "container=${ECS_SERVICE_NAME},name=VERSION_INFO,value=${CIRCLE_SHA1}_${CIRCLE_BUILD_NUM},container=${ECS_SERVICE_NAME},name=BUILD_DATE,value=\"$(date)\""
#          verify-revision-is-deployed: true
